# Generated by Django 6.0.6 on 2026-09-11 05:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0033_employee_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('request_type', models.CharField(choices=[('Late Arrival', 'Late Arrival Permission'), ('Clock In', 'Clock In Approval'), ('Clock Out', 'Clock Out Approval'), ('Permission', 'General Permission')], default='Late Arrival', max_length=50)),
                ('requested_time', models.TimeField(help_text='Expected / requested login or logout time')),
                ('reason', models.TextField(help_text='Reason for late arrival or permission')),
                ('token', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending Admin Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_requests', to='employees.employee')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_attendance_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
